# © 2025 Testsmith. Exclusive training material.
# Distributed to armin a (armin.arabshahi@gmail.com) on 2025-09-22.
# Licensed for personal learning only. No redistribution, copying, or public posting
# (including blogs, social media, GitHub, Gists, or forums). Do not remove this notice.
# Contact: info@testsmith.io
*** Settings ***
Documentation       LO-2.3.2    K2    Explain the execution artifacts generated by Robot Framework.
...
...                 Demo suite to show Robot Framework execution artifacts

Library             OperatingSystem


*** Test Cases ***
Passing Test
    [Documentation]    A test that always passes
    Log                 This is a passing test
    Should Be True      ${True}

Failing Test
    [Documentation]    A test that will fail to demonstrate logging
    [Tags]              failonpurpose
    Log                 This test will fail
    Should Be Equal     1                       2
